defaults:
  price:
    min: 10
    max: 30
  profitMargin:
    min: 0.3
  minUnitsSold: 100
  minGrowthRate: 0
  excludedCategories:
    - adult products
    - weapons
    - drugs

regions:
  th:
    price:
      min: 5
      max: 25
  id:
    price:
      min: 3
      max: 15
    minUnitsSold: 50

scraping:
  dailyDetailBudget: 300
  dailySearchBudget: 300
  freshness:
    detailRefreshDays: 7
    vocRefreshDays: 14
    shopRefreshDays: 7
